package code

var enUSText = map[int]string{
	SUCCESS:                   "Success",
	ErrorImageNotFound:        "Image not found",
	UploadImageSuccess:        "Upload image success",
	ErrorCreateDir:            "Create dir failed",
	SaveFileSuccess:           "Save file success",
	ErrorSaveFile:             "Save file failed",
	ErrorSaveFileData:         "Save file data failed",
	ErrorUploadQiNiu:          "Upload to qiniu failed",
	ErrorOpenFile:             "Open file failed",
	ErrorUploadQiNiuSuccess:   "Upload to qiniu success",
	ErrorMissingId:            "Missing id",
	ErrorFileNotFound:         "File not found",
	ErrorDeleteFile:           "Delete file failed",
	ErrorDeleteFileData:       "Delete file data failed",
	ErrorListFile:             "List file failed",
	ErrorCreateTheme:          "Create theme failed",
	ErrorGetTheme:             "Get theme failed",
	ErrorDeleteTheme:          "Delete theme failed",
	ErrorThemeNotFound:        "Theme not found",
	ErrorUpdateTheme:          "Update theme failed",
	ErrorRegisterMissingParam: "Missing param",
	ErrorUserExist:            "User exist",
	ErrorUserExistAccount:     "User exist account",
	ErrorUserExistNickname:    "User exist nickname",
	ErrorUserExistEmail:       "User exist email",
	ErrorUserExistPhone:       "User exist phone",
	ErrorCreateUser:           "Create user failed",
	ErrorGetQueryParam:        "Get query param failed",
}
