package code

var zhCNText = map[int]string{
	SUCCESS:                   "成功",
	ErrorImageNotFound:        "图片不存在",
	UploadImageSuccess:        "上传图片成功",
	ErrorCreateDir:            "创建文件夹失败",
	SaveFileSuccess:           "保存文件成功",
	ErrorSaveFile:             "保存文件失败",
	ErrorSaveFileData:         "保存文件信息到数据库失败",
	ErrorUploadQiNiu:          "七牛云上传失败",
	ErrorOpenFile:             "打开文件失败",
	ErrorUploadQiNiuSuccess:   "七牛云上传成功",
	ErrorMissingId:            "缺少id",
	ErrorFileNotFound:         "文件不存在",
	ErrorDeleteFile:           "删除文件失败",
	ErrorDeleteFileData:       "删除文件数据库失败",
	ErrorListFile:             "获取文件列表失败",
	ErrorCreateTheme:          "创建主题失败",
	ErrorGetTheme:             "获取主题失败",
	ErrorDeleteTheme:          "删除主题失败",
	ErrorThemeNotFound:        "主题不存在",
	ErrorUpdateTheme:          "主题更新失败",
	ErrorRegisterMissingParam: "注册用户缺少参数",
	ErrorUserExist:            "用户已存在",
	ErrorUserExistAccount:     "账号已存在",
	ErrorUserExistNickname:    "昵称已存在",
	ErrorUserExistEmail:       "邮箱已存在",
	ErrorUserExistPhone:       "手机号已存在",
	ErrorCreateUser:           "创建用户失败",
	ErrorGetQueryParam:        "获取查询参数失败",
}
